# SPDX-License-Identifier: GPL-3.0-or-later

[tool.briefcase]
project_name = "UAAccess"
bundle = "org.uaaccess"
version = "0.0.3"
url = "https://uaaccess.org"
license.file = "LICENSE"
author = "Dan Gililov, Ethin Probst, Ivan Soto, Carter Temm"
author_email = "N/A"

[tool.briefcase.app.uaaccess]
formal_name = "UAAccess"
description = "A screen-reader-accessible alternative to the Universal Audio Console software."
long_description = """UAAccess is a screen-reader friendly alternative to the UA console software.
"""
icon = "src/uaaccess/resources/uaaccess"
sources = [
    "src/uaaccess",
    "LICENSE",
]
test_sources = [
    "tests",
]

requires = [
    "blinker~=1.9",
    "clipboard~=0.0.4",
    "cysimdjson~=23.8 ; (sys_platform != 'darwin') and (platform_machine != 'x86_64')",
    "pedalboard~=0.9",
    "aiofiles~=24.1",
    "pygithub~=2.5",
    "aiohttp~=3.11",
    "packaging~=24.2",
]
test_requires = [    "pytest", "hypothesis"]


[tool.briefcase.app.uaaccess.macOS]
universal_build = true
requires = [
    "toga-cocoa~=0.4.4",
    "std-nslog~=1.0.0",
    "pyobjc~=10.3",
]


[tool.briefcase.app.uaaccess.linux]
requires = [
    "toga-gtk~=0.4.4",
]
supported = false


[tool.briefcase.app.uaaccess.linux.system.debian]
system_requires = [
    # Needed to compile pycairo wheel
    "libcairo2-dev",
    # Needed to compile PyGObject wheel
    "libgirepository1.0-dev",
]

system_runtime_requires = [
    # Needed to provide GTK and its GI bindings
    "gir1.2-gtk-3.0",
    "libgirepository-1.0-1",
    # Dependencies that GTK looks for at runtime
    "libcanberra-gtk3-module",
    # Needed to provide WebKit2 at runtime
    # "gir1.2-webkit2-4.0",
]
supported = false


[tool.briefcase.app.uaaccess.linux.system.rhel]
system_requires = [
    # Needed to compile pycairo wheel
    "cairo-gobject-devel",
    # Needed to compile PyGObject wheel
    "gobject-introspection-devel",
]

system_runtime_requires = [
    # Needed to support Python bindings to GTK
    "gobject-introspection",
    # Needed to provide GTK
    "gtk3",
    # Dependencies that GTK looks for at runtime
    "libcanberra-gtk3",
    # Needed to provide WebKit2 at runtime
    # "webkit2gtk3",
]
supported = false


[tool.briefcase.app.uaaccess.linux.system.suse]
system_requires = [
    # Needed to compile pycairo wheel
    "cairo-devel",
    # Needed to compile PyGObject wheel
    "gobject-introspection-devel",
]

system_runtime_requires = [
    # Needed to provide GTK
    "gtk3",
    # Needed to support Python bindings to GTK
    "gobject-introspection", "typelib(Gtk) = 3.0",
    # Dependencies that GTK looks for at runtime
    "libcanberra-gtk3-0",
    # Needed to provide WebKit2 at runtime
    # "libwebkit2gtk3",
    # "typelib(WebKit2)",
]
supported = false


[tool.briefcase.app.uaaccess.linux.system.arch]
system_requires = [
    # Needed to compile pycairo wheel
    "cairo",
    # Needed to compile PyGObject wheel
    "gobject-introspection",
    # Runtime dependencies that need to exist so that the
    # Arch package passes final validation.
    # Needed to provide GTK
    "gtk3",
    # Dependencies that GTK looks for at runtime
    "libcanberra",
    # Needed to provide WebKit2
    # "webkit2gtk",
]

system_runtime_requires = [
    # Needed to provide GTK
    "gtk3",
    # Needed to provide PyGObject bindings
    "gobject-introspection-runtime",
    # Dependencies that GTK looks for at runtime
    "libcanberra",
    # Needed to provide WebKit2 at runtime
    # "webkit2gtk",
]
supported = false


[tool.briefcase.app.uaaccess.linux.appimage]
manylinux = "manylinux_2_28"

system_requires = [
    # Needed to compile pycairo wheel
    "cairo-gobject-devel",
    # Needed to compile PyGObject wheel
    "gobject-introspection-devel",
    # Needed to provide GTK
    "gtk3-devel",
    # Dependencies that GTK looks for at runtime, that need to be
    # in the build environment to be picked up by linuxdeploy
    "libcanberra-gtk3",
    "PackageKit-gtk3-module",
    "gvfs-client",
]

linuxdeploy_plugins = [
    "DEPLOY_GTK_VERSION=3 gtk",
]
supported = false


[tool.briefcase.app.uaaccess.linux.flatpak]
flatpak_runtime = "org.gnome.Platform"
flatpak_runtime_version = "45"
flatpak_sdk = "org.gnome.Sdk"
supported = false


[tool.briefcase.app.uaaccess.windows]
requires = [
    "toga-winforms~=0.4.4",
    "cytolk~=0.1.13",
    "win32more~=0.5",
]


# Mobile deployments
[tool.briefcase.app.uaaccess.iOS]
requires = [
    "toga-iOS~=0.4.4",
    "std-nslog~=1.0.0",
]
supported = false


[tool.briefcase.app.uaaccess.android]
requires = [
    "toga-android~=0.4.4",
]
base_theme = "Theme.MaterialComponents.Light.DarkActionBar"
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.6.1",
    "com.google.android.material:material:1.11.0",
    # Needed for DetailedList
    "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0",
]
supported = false


# Web deployments
[tool.briefcase.app.uaaccess.web]
requires = [
    "toga-web~=0.4.4",
]
style_framework = "Shoelace v2.3"
supported = false

