name: Build and Package

on:
  workflow_dispatch:

jobs:
  mac_build:
    name: Build and Package on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies and run build script
        run: |
          python -m venv uaaccess_env
          source uaaccess_env/bin/activate
          pip install --upgrade pip
          cd builder
          python build_uaaccess.py
          python build_uaaccess.py zip
        env:
          BRIEFCASE_PLATFORM: macOS

      - name: Find installer package
        id: find_installer
        run: |
          artifact=$(ls dist/*.pkg 2>/dev/null | head -n 1)
          if [ -z "$artifact" ]; then
            echo "Error: No .pkg file found in the dist directory."
            exit 1
          fi
          artifact_name=$(basename "$artifact")
          echo "artifact_path=$artifact" >> $GITHUB_OUTPUT
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

      - name: Find portable package
        id: find_portable
        run: |
          artifact=$(ls dist/*.zip 2>/dev/null | head -n 1)
          if [ -z "$artifact" ]; then
            echo "Error: No .zip file found in the dist directory."
            exit 1
          fi
          artifact_name=$(basename "$artifact")
          echo "artifact_path=$artifact" >> $GITHUB_OUTPUT
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_installer.outputs.artifact_name }}
          path: ${{ steps.find_installer.outputs.artifact_path }}
          retention-days: 1

      - name: Upload portable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_portable.outputs.artifact_name }}
          path: ${{ steps.find_portable.outputs.artifact_path }}
          retention-days: 1

  windows_build:
    name: Build and Package on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Visual Studio Build Tools
        run: |
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart"

      - name: Install dependencies and run build script
        run: |
          python -m venv uaaccess_env
          uaaccess_env\Scripts\activate
          pip install --upgrade pip
          cd builder
          python build_uaaccess.py
          python build_uaaccess.py zip
        env:
          BRIEFCASE_PLATFORM: windows

      - name: Find installer package
        id: find_installer
        shell: pwsh
        run: |
          $pattern = 'dist\*.msi'
          $artifact = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Select-Object -First 1
          if (-not $artifact) {
            Write-Error "Error: No .msi file found in the dist directory."
            exit 1
          }
          $artifactPath = $artifact.FullName
          $artifactName = $artifact.Name
          "$env:GITHUB_OUTPUT" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "artifact_path=$artifactPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "artifact_name=$artifactName" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Find portable package
        id: find_portable
        shell: pwsh
        run: |
          $pattern = 'dist\*.zip'
          $artifact = Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Select-Object -First 1
          if (-not $artifact) {
            Write-Error "Error: No .zip file found in the dist directory."
            exit 1
          }
          $artifactPath = $artifact.FullName
          $artifactName = $artifact.Name
          "$env:GITHUB_OUTPUT" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "artifact_path=$artifactPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "artifact_name=$artifactName" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_installer.outputs.artifact_name }}
          path: ${{ steps.find_installer.outputs.artifact_path }}
          retention-days: 1

      - name: Upload portable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_portable.outputs.artifact_name }}
          path: ${{ steps.find_installer.outputs.artifact_path }}
          retention-days: 1
